name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Resume.tex
      - name: Check pdf file
        run: |
          file Resume.pdf | grep -q ' PDF '
      - name: Create Release file 
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Resume.pdf
          name: Resume version ${{ github.ref_name }}