name: Build LaTeX document
on: [push,pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Resume.tex
      - name: Check pdf file
        run: |
          file Resume.pdf | grep -q ' PDF '
      - name: Create Release file 
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Resume.pdf
          name: Resume version ${{ github.ref_name }}
      - name: Add pdf to repository
        run: |
              git config --global user.name 'GitHub Actions'
              git config --global user.email 'actions@github.com'
              git add Resume.pdf
              git commit -m "Update generated PDFs" || echo "No changes to commit"
              git push